### ISSUE TITLE
Returning wrong stem for English adjective

### ISSUE THREAD

**Issue by JunaidQadirB** [wamania/php-stemmer#1]
I'm about to fork this stemmer for my language but before I could start I just tried a word using the English stemmer.

I gave it the adjective **unethical** but to my surprise it returned **uneth**  whereas it should have spitted **ethic** as
Can you please look into it.

**Comment by wamania** [comment]
Hello JeyKeu

Thanks for your interest.
This stemmer is a strict implementation of the snowball stemmer 
http://snowballstem.org/algorithms/english/stemmer.html

If you look deeper in the algorithm , you will see that it is never question of prefix, but only suffix.
You can see in the output example file :
https://raw.githubusercontent.com/snowballstem/snowball-data/master/english/output.txt
there are a lot of "un..." : unask, unattach, unavail, etc

It should be done, but not here. I want to keep it like a pure and strict implementation of the snowball algorithm.
