### ISSUE TITLE
PHP 8.2 and voku/portable-utf8

### ISSUE THREAD

**Issue by hirasso** [wamania/php-stemmer#31]
Hi there! I'm in the process of upgrading to PHP 8.2. Getting the following warnings:

```
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 4653

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 4664

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 5731

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 5742

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 13398

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 13398

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 13409

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 13409
```

I checked the [latest release of voku/portable-utf8](https://github.com/voku/portable-utf8/releases/tag/6.0.13) and it seems like this has been fixed on their end. Could it be possible that you could fix this by updating the dependency in your composer.json to the version that fixes this?

https://github.com/wamania/php-stemmer/blob/8ea32b6fa27d6888587fe860b64a8763525c5a66/composer.json#L14

Thanks a lot for your help!

**Comment by HLeithner** [comment]
it's already fixed in 3.0.1 see https://github.com/wamania/php-stemmer/releases/tag/v3.0.1 I'm closing this, feel free to reopen if the error still exists.

**Comment by hirasso** [comment]
Woaa that was fast, thank you for your response @HLeithner ! 

Peculiar, I seem to still have to understand how exactly composer works. Just changing the version to `^3.0` didn't pull in the latest version of `voku/portable-utf8` for me. I had to do

```
composer remove wamania/php-stemmer
composer require wamania/php-stemmer
```

That worked.

**Comment by HLeithner** [comment]
changing to "^3.0" and composer update should work.

**Comment by hirasso** [comment]
Ahh right, forgot about `composer update`! Thank you, much appreciated.
