### ISSUE TITLE
php 7.4

### ISSUE THREAD

**Issue by brianteeman** [wamania/php-stemmer#5]
We discovered https://github.com/joomla/joomla-cms/issues/27329 that the code in the utf8.php file is not compatible with php7.4 as it produces several deprecated notices like this

> PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated

Is this something that is resolved in v2? Is v2 backwards compatible?

**Comment by tabennett** [comment]
We are having this same issue as well. Would be more than willing to PR this if need be; This is the last issue with have left in order to get our test suite green for PHP 7.4

**Comment by wamania** [comment]
Hi
Yes with v2, i will change the UTF8 class using voku/portable-utf8
https://github.com/wamania/php-stemmer/blob/v2/composer.json#L14

**Comment by wamania** [comment]
tagged v1.3
thanks et sorry for the delay
